define([], function() {
  return {
    "PropertyPaneDescription": "",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "",
    "DescriptionNameFieldLabel": "",
    "PropertyPaneTitle": "Enter Cards Title",
    "PropertyPaneTitle2": "Enter Picture Slider Title",
    "ListNameFieldLabel": "Enter your Page library name below:",
    "NewsCounterFieldLabel": "Slide to set the number of Cards to display:",
    "TitleFieldLabel": "Cards Title:",
    "TitleFieldLabel2": "Picture Slider Title:",
    "CharCounterFieldLabel": "Slide to set the max. number of characters per Card content",
    "GeneralGroupName": "General",
    "showThumbsFieldLabel":"Show Thumbs",
    "autoPlayFieldLabel":"Auto Play",
    "infiniteLoopFieldLabel":"Infinite Loop",
    "intervalFieldLabel":"Set Interval",
    "showArrowsFieldLabel":"Show Arrows",
    "showStatusFieldLabel":"Show Status",
    "swipeableFieldLabel":"Swipeable Option",
    "stopOnHoverFieldLabel":"Stop on Hover",
    "showIndicatorsFieldLabel":"Show Indicators",
    "transitionTimeFieldLabel":"Transition Time",
    "newsCardBgColorFieldLabel":"Card Color",
    "listName2FieldLabel": "Enter your image library name below:",
    "SlideCounterFieldLabel": "Set Number of Slides to Load",
    "showLegendFieldLabel": "Show Legend",
    "maxHeightFieldLabel":"Set Max-Height",
    "maxWidthFieldLabel":"Set Max-Width",
    "navmenuitem1FieldLabel":"Label Name for Nav-Menu item 1: ",
    "navmenuitem2FieldLabel":"Label Name for Nav-Menu item 2: "
  }
});
